name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Enable Corepack for yarn
        run: corepack enable
      - name: Install dependencies
        run: yarn
      - name: Generate GraphQL types
        run: yarn prebuild
      - name: Type Check
        run: yarn tsc
      - name: Run ESLint
        run: yarn eslint --ext .ts,.tsx src
