name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          cache: yarn
      - name: Install dependencies
        run: corepack enable && yarn --frozen-lockfile
      - name: Generate GraphQL types
        run: yarn prebuild
      - name: Type Check
        run: yarn tsc
      - name: Run ESLint
        run: yarn eslint
      - name: Build static site
        run: cp .env.development .env.local && yarn build && yarn export
      - uses: actions/upload-artifact@v3
        with:
          name: public_html
          path: out/
